baseURL = 'https://example.org/'
defaultContentLanguage = 'he'

[languages]
  [languages.he]
    disabled = false
    languageCode = 'he-IL'
    languageDirection = 'rtl'
    languageName = 'עברית'
    title = 'אתר הוגו חדש'
    weight = 0
